---
- hosts: leaf
  gather_facts: false

  tasks:
  - name: Configure VLAN and assign VNI
    nxos_vlans:
      config:
      - vlan_id: 50
        name: vlan50
        mapped_vni: 100500
  
  - name: Configure VNI on NVE interface
    nxos_vxlan_vtep_vni:
      interface: nve1
      multicast_group: "239.0.0.50"
      vni: 100500
  
  - name: Configure VNI on EVPN
    cisco.nxos.nxos_evpn_vni:
      vni: 100500
      route_distinguisher: auto
      route_target_import: auto
      route_target_export: auto

  - name: Configure switchport
    cisco.nxos.nxos_command:
      commands: 
      - configure terminal
      - interface ethernet 1/3
      - switchport
      - switchport mode access
      - switchport access vlan 50
      - spanning-tree port type edge
      - no shutdown