---
- hosts: all
  gather_facts: false

  tasks:
    - name: "Configure User"
      nxos_user:
        name: cisco
        configured_password:
        role: network-admin
        state: present
        update_password: always
