---
- hosts: all
  gather_facts: false

  tasks:
  - name: "Enable NX-API"
    nxos_feature:
      feature: nxapi
      state: enabled
      
  - name: "Enable Restconf"
    nxos_feature:
      feature: restconf
      state: enabled