---
- hosts: all
  gather_facts: false

  tasks:
  
  - name: "Login to device and get API token"
    uri:
      url: https://{{ansible_host}}/api/aaaLogin.json
      method: POST
      return_content: yes
      body: '{ "aaaUser": { "attributes": { "name": "", "pwd": "" }}}'
      body_format: json
      status_code: 200,201,204
      validate_certs: no
    register: token
  
  - name: "Token Data"
    ansible.builtin.debug:
      var: token.json.imdata[0].aaaLogin.attributes.token