all:
  children:
    spine:
      hosts:
        n9kv-s1:
          ansible_host: 10.82.128.47
          ansible_network_os: nxos
          leaf_uplink_interface: eth1/1
          spine_downlink_1: eth1/1
          spine_downlink_2: eth1/2
          underlay_loopback_ip: 192.168.0.1
          vtep_loopback_ip: 10.168.0.1
          bgp_rid: 1.1.1.1
          
        n9kv-s2:
          ansible_host: 10.82.128.48
          ansible_network_os: nxos
          leaf_uplink_interface: eth1/2
          spine_downlink_1: eth1/1
          spine_downlink_2: eth1/2
          underlay_loopback_ip: 192.168.0.2
          vtep_loopback_ip: 10.168.0.2
          bgp_rid: 1.1.1.2
          
    leaf:
      hosts:
        n9kv-l1:
          ansible_host: 10.82.128.49
          ansible_network_os: nxos
          spine_downlink_interface: eth1/1
          leaf_uplink_1: eth1/1
          leaf_uplink_2: eth1/2
          underlay_loopback_ip: 192.168.0.11
          vtep_loopback_ip: 10.168.0.11
          bgp_rid: 2.1.1.1

        n9kv-l2:
          ansible_host: 10.82.128.50
          ansible_network_os: nxos
          spine_downlink_interface: eth1/2
          leaf_uplink_1: eth1/1
          leaf_uplink_2: eth1/2
          underlay_loopback_ip: 192.168.0.12
          vtep_loopback_ip: 10.168.0.12
          bgp_rid: 2.1.1.2