---
- name: "Enable Loopback Interfaces"
  uri:
    url: https://{{ansible_host}}{{base_uri}}/intf-items/lb-items/
    method: POST
    headers:
      Authorization: "{{ authorization }}"
      Cookie: "{{ cookie }}"
      Accept: 'application/yang.data+json'
      Content-Type: 'application/yang.data+json'
    return_content: yes
    body: "{{ lookup('template','base_loopback_config.json.j2') }}"
    body_format: json
    status_code: 200,201,204
    validate_certs: no

- name: "Configure Layer 3 Physical Interfaces"
  uri:
    url: https://{{ansible_host}}{{base_uri}}/intf-items/phys-items/
    method: PATCH
    headers:
      Authorization: "{{ authorization }}"
      Cookie: "{{ cookie }}"
      Accept: 'application/yang.data+json'
      Content-Type: 'application/yang.data+json'
    return_content: yes
    body: "{{ lookup('template','base_ethernet_config.json.j2') }}"
    body_format: json
    status_code: 200,201,204
    validate_certs: no

- name: "Configure IPv4 on Loopback and Physical Interfaces"
  uri:
    url: https://{{ansible_host}}{{base_uri}}/ipv4-items/inst-items/dom-items/Dom-list=default/if-items
    method: POST
    headers:
      Authorization: "{{ authorization }}"
      Cookie: "{{ cookie }}"
      Accept: 'application/yang.data+json'
      Content-Type: 'application/yang.data+json'
    return_content: yes
    body: "{{ lookup('template','ipv4_interface_config.json.j2') }}"
    body_format: json
    status_code: 200,201,204
    validate_certs: no

- name: "Configure PIM"
  uri:
    url: https://{{ansible_host}}{{base_uri}}/pim-items/inst-items/dom-items/Dom-list=default
    method: POST
    headers:
      Authorization: "{{ authorization }}"
      Cookie: "{{ cookie }}"
      Accept: 'application/yang.data+json'
      Content-Type: 'application/yang.data+json'
    return_content: yes
    body: "{{ lookup('template','pim_config.json.j2') }}"
    body_format: json
    status_code: 200,201,204
    validate_certs: no

- name: "Configure OSPF"
  uri:
    url: https://{{ansible_host}}{{base_uri}}/ospf-items
    method: POST
    headers:
      Authorization: "{{ authorization }}"
      Cookie: "{{ cookie }}"
      Accept: 'application/yang.data+json'
      Content-Type: 'application/yang.data+json'
    return_content: yes
    body: "{{ lookup('template','ospf_config.json.j2') }}"
    body_format: json
    status_code: 200,201,204
    validate_certs: no

- name: "Configure BGP"
  uri:
    url: https://{{ansible_host}}{{base_uri}}/bgp-items
    method: POST
    headers:
      Authorization: "{{ authorization }}"
      Cookie: "{{ cookie }}"
      Accept: 'application/yang.data+json'
      Content-Type: 'application/yang.data+json'
    return_content: yes
    body: "{{ lookup('template','bgp_config.json.j2') }}"
    body_format: json
    status_code: 200,201,204
    validate_certs: no