---
- name: "Configure system"
  uri:
    url: https://{{ansible_host}}{{base_uri}}
    method: PATCH
    headers:
      Authorization: "{{ authorization }}"
      Cookie: "{{ cookie }}"
      Accept: 'application/yang.data+json'
      Content-Type: 'application/yang.data+json'
    return_content: yes
    body: "{{ lookup('template','system.json.j2') }}"
    body_format: json
    status_code: 204
    validate_certs: no

- name: "Configure features"
  uri:
    url: https://{{ansible_host}}{{base_uri}}/fm-items
    method: PUT
    headers:
      Authorization: "{{ authorization }}"
      Cookie: "{{ cookie }}"
      Accept: 'application/yang.data+json'
      Content-Type: 'application/yang.data+json'
    return_content: yes
    body: "{{ lookup('template','features.json.j2') }}"
    body_format: json
    status_code: 200,201,204
    validate_certs: no
  